use crate::{analysis::{AuditResult,Scenario},dexscreener::EnrichedMarket,events::{MarketEvent,SecuritySnapshot},portfolio::PaperPosition};
use reqwest::Client; use serde_json::{json,Value}; use thiserror::Error;
#[derive(Debug,Error)]pub enum PersistenceError{#[error("http error: {0}")]Http(#[from]reqwest::Error),#[error("supabase returned {0}: {1}")]Status(u16,String)}
#[derive(Clone)]pub struct SupabaseStore{base:String,key:String,client:Client}
impl SupabaseStore{
 pub fn from_env()->Option<Self>{Some(Self{base:std::env::var("SUPABASE_URL").ok()?,key:std::env::var("SUPABASE_SECRET_KEY").or_else(|_|std::env::var("SUPABASE_SERVICE_ROLE_KEY")).ok()?,client:Client::new()})}
 async fn post(&self,table:&str,body:Value)->Result<(),PersistenceError>{let r=self.client.post(format!("{}/rest/v1/{}",self.base,table)).header("apikey",&self.key).header("Authorization",format!("Bearer {}",self.key)).header("Content-Type","application/json").header("Prefer","return=minimal").json(&body).send().await?;if r.status().is_success(){Ok(())}else{Err(PersistenceError::Status(r.status().as_u16(),r.text().await.unwrap_or_default()))}}
 async fn upsert(&self,table:&str,body:Value,on_conflict:&str)->Result<(),PersistenceError>{let r=self.client.post(format!("{}/rest/v1/{}?on_conflict={}",self.base,table,on_conflict)).header("apikey",&self.key).header("Authorization",format!("Bearer {}",self.key)).header("Content-Type","application/json").header("Prefer","resolution=merge-duplicates,return=minimal").json(&body).send().await?;if r.status().is_success(){Ok(())}else{Err(PersistenceError::Status(r.status().as_u16(),r.text().await.unwrap_or_default()))}}
 pub async fn token(&self,mint:&str,symbol:Option<&str>,created_ms:u64)->Result<(),PersistenceError>{self.upsert("tokens",json!({"mint":mint,"symbol":symbol,"first_seen_at":chrono::DateTime::<chrono::Utc>::from_timestamp_millis(created_ms as i64),"last_seen_at":chrono::Utc::now(),"status":"observed"}),"mint").await}
 pub async fn security(&self,s:&SecuritySnapshot)->Result<(),PersistenceError>{self.post("token_security",json!({"mint":s.mint,"observed_at":chrono::Utc::now(),"mint_authority_revoked":s.mint_authority_revoked,"freeze_authority_revoked":s.freeze_authority_revoked,"rug_risk_score":s.top_10_non_bonding_pct.map(|v|v.min(100.0)),"honeypot_risk_score":null,"scam_risk_score":null,"security_status":"observed","evidence":["direct mint account inspection","top-holder concentration from token-largest-accounts"]})).await}
 pub async fn trade(&self,e:&MarketEvent)->Result<(),PersistenceError>{self.post("market_trades",json!({"mint":e.mint,"signature":e.signature,"slot":e.slot,"trader":e.trader,"side":match e.is_buy{Some(true)=>"buy",Some(false)=>"sell",None=>"unknown"},"amount_tokens":e.token_amount,"amount_sol":e.sol_amount,"observed_at":chrono::Utc::now()})).await}
 pub async fn market(&self,mint:&str,m:&EnrichedMarket)->Result<(),PersistenceError>{if let Some(pool)=&m.pool.pool_address{self.upsert("liquidity_pools",json!({"mint":mint,"dex":m.pool.dex,"pool_address":pool,"liquidity_usd":m.liquidity_usd,"price_usd":m.price_usd,"observed_at":chrono::Utc::now()}),"mint,dex,pool_address").await?;}Ok(())}
 pub async fn candle(&self,mint:&str,m:&EnrichedMarket)->Result<(),PersistenceError>{let bucket=chrono::Utc::now().timestamp()/60*60;self.upsert("market_candles",json!({"mint":mint,"timeframe":"1m","bucket_start":chrono::DateTime::<chrono::Utc>::from_timestamp(bucket,0),"open":m.price_usd,"high":m.price_usd,"low":m.price_usd,"close":m.price_usd,"volume_usd":m.volume_5m_usd,"buy_volume_usd":null,"sell_volume_usd":null,"buy_count":m.buy_count_5m,"sell_count":m.sell_count_5m,"unique_buyers":null,"unique_sellers":null,"vwap":m.price_usd}),"mint,timeframe,bucket_start").await}
 pub async fn audit(&self,mint:&str,a:&AuditResult)->Result<(),PersistenceError>{self.post("audit_reports",json!({"mint":mint,"audit_version":"evidence-v1","verdict":a.verdict,"rug_confidence":a.rug_confidence,"honeypot_confidence":a.honeypot_confidence,"scam_confidence":a.scam_confidence,"liquidity_confidence":null,"holder_confidence":null,"market_structure_confidence":null,"momentum_confidence":null,"data_quality_confidence":a.audit_score,"critical_flags":a.reasons,"warnings":a.reasons,"evidence":a.evidence,"model_version":"evidence-v1","raw":{"audit_score":a.audit_score}})).await}
 pub async fn scenarios(&self,mint:&str,items:&[Scenario])->Result<(),PersistenceError>{for s in items{self.post("scenario_forecasts",json!({"mint":mint,"horizon":s.horizon,"multiple":s.multiple,"probability":s.probability,"confidence_low":(s.probability*0.75).max(0.0),"confidence_high":(s.probability*1.15).min(1.0),"model_version":"evidence-v1","feature_snapshot":s.basis})).await?;}Ok(())}
 pub async fn strategy(&self,mint:&str,decision:&str,score:f64,buy:f64,sell:f64,buyers:usize,sellers:usize,evidence:Value)->Result<(),PersistenceError>{self.post("risk_events",json!({"mint":mint,"severity":if decision=="ENTRY_CANDIDATE"{"info"}else{"warning"},"event_type":"strategy_decision","message":decision,"evidence":{"score":score,"buy_sol_1m":buy,"sell_sol_1m":sell,"unique_buyers":buyers,"unique_sellers":sellers,"details":evidence}})).await}
 pub async fn paper_open(&self,p:&PaperPosition)->Result<(),PersistenceError>{self.post("paper_positions",json!({"id":p.id,"mint":p.mint,"status":"open","entry_price_usd":p.entry_price,"quantity_tokens":p.quantity,"remaining_tokens":p.quantity,"metadata":{"entry_sol":p.entry_sol,"source":"evidence-engine"}})).await}
 pub async fn paper_update(&self,p:&PaperPosition)->Result<(),PersistenceError>{let url=format!("{}/rest/v1/paper_positions?id=eq.{}",self.base,p.id);let r=self.client.patch(url).header("apikey",&self.key).header("Authorization",format!("Bearer {}",self.key)).header("Content-Type","application/json").header("Prefer","return=minimal").json(&json!({"status":match p.state{crate::portfolio::PositionState::Closed=>"closed",crate::portfolio::PositionState::PartialExit=>"partial",_=>"open"},"exit_price_usd":if matches!(p.state,crate::portfolio::PositionState::Closed){Some(p.peak_price)}else{None},"realized_roi_pct":(p.realized_pnl_sol/p.entry_sol.max(0.0000001))*100.0,"max_favorable_excursion_pct":((p.peak_price/p.entry_price)-1.0)*100.0,"metadata":{"realized_pnl_sol":p.realized_pnl_sol}})).send().await?;if r.status().is_success(){Ok(())}else{Err(PersistenceError::Status(r.status().as_u16(),r.text().await.unwrap_or_default()))}}
 pub async fn health(&self,component:&str,status:&str,latency_ms:Option<f64>)->Result<(),PersistenceError>{self.upsert("engine_health",json!({"component":component,"status":status,"last_heartbeat":chrono::Utc::now(),"latency_ms":latency_ms,"details":{"mode":"observe"}}),"component").await}
}
