use crate::{analysis::{AuditResult,Scenario}, dexscreener::EnrichedMarket, events::{MarketEvent,SecuritySnapshot}};
use reqwest::Client; use serde_json::{json,Value}; use thiserror::Error;
#[derive(Debug,Error)] pub enum PersistenceError { #[error("http error: {0}")] Http(#[from] reqwest::Error), #[error("supabase returned {0}: {1}")] Status(u16,String) }
#[derive(Clone)] pub struct SupabaseStore { base:String,key:String,client:Client }
impl SupabaseStore {
 pub fn from_env()->Option<Self>{Some(Self{base:std::env::var("SUPABASE_URL").ok()?,key:std::env::var("SUPABASE_SECRET_KEY").or_else(|_|std::env::var("SUPABASE_SERVICE_ROLE_KEY")).ok()?,client:Client::new()})}
 async fn post(&self,table:&str,body:Value)->Result<(),PersistenceError>{let r=self.client.post(format!("{}/rest/v1/{}",self.base,table)).header("apikey",&self.key).header("Authorization",format!("Bearer {}",self.key)).header("Content-Type","application/json").header("Prefer","return=minimal").json(&body).send().await?;if r.status().is_success(){Ok(())}else{Err(PersistenceError::Status(r.status().as_u16(),r.text().await.unwrap_or_default()))}}
 pub async fn token(&self,mint:&str,symbol:Option<&str>,_created_ms:u64)->Result<(),PersistenceError>{self.post("tokens",json!({"mint":mint,"symbol":symbol})).await}
 pub async fn security(&self,s:&SecuritySnapshot)->Result<(),PersistenceError>{self.post("security_snapshots",json!({"mint":s.mint,"mint_authority_revoked":s.mint_authority_revoked,"freeze_authority_revoked":s.freeze_authority_revoked,"top_10_non_bonding_pct":s.top_10_non_bonding_pct,"liquidity_usd":s.liquidity_usd,"risk_state":"observed","reasons":[],"evidence":["direct mint account inspection"]})).await}
 pub async fn trade(&self,e:&MarketEvent)->Result<(),PersistenceError>{self.post("market_events",json!({"event_id":e.event_id,"mint":e.mint,"source":format!("{:?}",e.source),"kind":format!("{:?}",e.kind),"slot":e.slot,"signature":e.signature,"observed_at":chrono::Utc::now(),"sol_amount":e.sol_amount,"token_amount":e.token_amount,"is_buy":e.is_buy,"trader":e.trader})).await}
 pub async fn market(&self,mint:&str,m:&EnrichedMarket)->Result<(),PersistenceError>{self.post("market_snapshots",json!({"mint":mint,"price_usd":m.price_usd,"fdv_usd":m.fdv_usd,"liquidity_usd":m.pool.evidence.first().and_then(|_|Some(0.0)),"volume_5m_usd":m.volume_5m_usd,"volume_1h_usd":m.volume_1h_usd,"buys_5m":m.buy_count_5m,"sells_5m":m.sell_count_5m,"dex":m.pool.dex,"pool_address":m.pool.pool_address})).await}
 pub async fn audit(&self,mint:&str,a:&AuditResult)->Result<(),PersistenceError>{self.post("token_audits",json!({"mint":mint,"verdict":a.verdict,"audit_score":a.audit_score,"rug_confidence":a.rug_confidence,"honeypot_confidence":a.honeypot_confidence,"scam_confidence":a.scam_confidence,"reasons":a.reasons,"evidence":a.evidence,"model_version":"evidence-v1"})).await}
 pub async fn scenarios(&self,mint:&str,items:&[Scenario])->Result<(),PersistenceError>{for s in items{self.post("scenario_forecasts",json!({"mint":mint,"multiple":s.multiple,"probability":s.probability,"horizon":s.horizon,"basis":s.basis,"model_version":"evidence-v1"})).await?;}Ok(())}
 pub async fn strategy(&self,mint:&str,decision:&str,score:f64,buy:f64,sell:f64,buyers:usize,sellers:usize,evidence:Value)->Result<(),PersistenceError>{self.post("strategy_decisions",json!({"mint":mint,"decision":decision,"score":score,"buy_sol_1m":buy,"sell_sol_1m":sell,"unique_buyers_1m":buyers,"unique_sellers_1m":sellers,"evidence":evidence})).await}
 pub async fn health(&self,component:&str,status:&str,latency_ms:Option<f64>)->Result<(),PersistenceError>{self.post("engine_health",json!({"component":component,"mode":"observe","rpc_ok":status=="healthy","pumpportal_ok":status=="healthy","rpc_latency_ms":latency_ms.map(|v|v as i64),"last_error":if status=="healthy"{Value::Null}else{json!(status)}})).await}
}
