use crate::{analysis::{AuditResult,Scenario}, dexscreener::EnrichedMarket, events::{MarketEvent,SecuritySnapshot}, portfolio::PaperPosition};
use reqwest::Client; use serde_json::{json,Value}; use thiserror::Error;
#[derive(Debug,Error)] pub enum PersistenceError{#[error("http error: {0}")]Http(#[from]reqwest::Error),#[error("supabase returned {0}: {1}")]Status(u16,String)}
#[derive(Clone)]pub struct SupabaseStore{base:String,key:String,client:Client}
impl SupabaseStore{
 pub fn from_env()->Option<Self>{Some(Self{base:std::env::var("SUPABASE_URL").ok()?,key:std::env::var("SUPABASE_SECRET_KEY").or_else(|_|std::env::var("SUPABASE_SERVICE_ROLE_KEY")).ok()?,client:Client::new()})}
 async fn post(&self,table:&str,body:Value)->Result<(),PersistenceError>{let r=self.client.post(format!("{}/rest/v1/{}",self.base,table)).header("apikey",&self.key).header("Authorization",format!("Bearer {}",self.key)).header("Content-Type","application/json").header("Prefer","return=minimal").json(&body).send().await?;if r.status().is_success(){Ok(())}else{Err(PersistenceError::Status(r.status().as_u16(),r.text().await.unwrap_or_default()))}}
 async fn upsert(&self,table:&str,body:Value,on_conflict:&str)->Result<(),PersistenceError>{let r=self.client.post(format!("{}/rest/v1/{}?on_conflict={}",self.base,table,on_conflict)).header("apikey",&self.key).header("Authorization",format!("Bearer {}",self.key)).header("Content-Type","application/json").header("Prefer","resolution=merge-duplicates,return=minimal").json(&body).send().await?;if r.status().is_success(){Ok(())}else{Err(PersistenceError::Status(r.status().as_u16(),r.text().await.unwrap_or_default()))}}
 pub async fn token(&self,mint:&str,symbol:Option<&str>,_created_ms:u64)->Result<(),PersistenceError>{self.upsert("tokens",json!({"mint":mint,"symbol":symbol}),"mint").await}
 pub async fn security(&self,s:&SecuritySnapshot)->Result<(),PersistenceError>{self.post("security_snapshots",json!({"mint":s.mint,"mint_authority_revoked":s.mint_authority_revoked,"freeze_authority_revoked":s.freeze_authority_revoked,"top_10_non_bonding_pct":s.top_10_non_bonding_pct,"liquidity_usd":s.liquidity_usd,"risk_state":"observed","reasons":[],"evidence":["direct mint account inspection"]})).await}
 pub async fn trade(&self,e:&MarketEvent)->Result<(),PersistenceError>{self.post("market_events",json!({"event_id":e.event_id,"mint":e.mint,"source":format!("{:?}",e.source),"kind":format!("{:?}",e.kind),"slot":e.slot,"signature":e.signature,"observed_at":chrono::Utc::now(),"sol_amount":e.sol_amount,"token_amount":e.token_amount,"is_buy":e.is_buy,"trader":e.trader})).await}
 pub async fn market(&self,mint:&str,m:&EnrichedMarket)->Result<(),PersistenceError>{self.post("market_snapshots",json!({"mint":mint,"price_usd":m.price_usd,"fdv_usd":m.fdv_usd,"liquidity_usd":m.liquidity_usd,"volume_5m_usd":m.volume_5m_usd,"volume_1h_usd":m.volume_1h_usd,"buys_5m":m.buy_count_5m,"sells_5m":m.sell_count_5m,"dex":m.pool.dex,"pool_address":m.pool.pool_address})).await}
 pub async fn candle(&self,mint:&str,m:&EnrichedMarket)->Result<(),PersistenceError>{let bucket=chrono::Utc::now().timestamp()/60*60;self.upsert("market_candles",json!({"mint":mint,"interval":"1m","bucket_start":chrono::DateTime::<chrono::Utc>::from_timestamp(bucket,0),"open":m.price_usd,"high":m.price_usd,"low":m.price_usd,"close":m.price_usd,"volume_usd":m.volume_5m_usd,"buy_volume_usd":null,"sell_volume_usd":null,"trades":m.buy_count_5m+m.sell_count_5m,"unique_buyers":null,"unique_sellers":null}),"mint,interval,bucket_start").await}
 pub async fn audit(&self,mint:&str,a:&AuditResult)->Result<(),PersistenceError>{self.post("token_audits",json!({"mint":mint,"verdict":a.verdict,"audit_score":a.audit_score,"rug_confidence":a.rug_confidence,"honeypot_confidence":a.honeypot_confidence,"scam_confidence":a.scam_confidence,"reasons":a.reasons,"evidence":a.evidence,"model_version":"evidence-v1"})).await}
 pub async fn scenarios(&self,mint:&str,items:&[Scenario])->Result<(),PersistenceError>{for s in items{self.post("scenario_forecasts",json!({"mint":mint,"multiple":s.multiple,"probability":s.probability,"horizon":s.horizon,"basis":s.basis,"model_version":"evidence-v1"})).await?;}Ok(())}
 pub async fn strategy(&self,mint:&str,decision:&str,score:f64,buy:f64,sell:f64,buyers:usize,sellers:usize,evidence:Value)->Result<(),PersistenceError>{self.post("strategy_decisions",json!({"mint":mint,"decision":decision,"score":score,"buy_sol_1m":buy,"sell_sol_1m":sell,"unique_buyers_1m":buyers,"unique_sellers_1m":sellers,"evidence":evidence})).await}
 pub async fn paper_open(&self,p:&PaperPosition)->Result<(),PersistenceError>{self.post("paper_positions",json!({"id":p.id,"mint":p.mint,"entry_price":p.entry_price,"quantity":p.quantity,"invested_sol":p.entry_sol,"status":"open","peak_price":p.peak_price})).await}
 pub async fn paper_update(&self,p:&PaperPosition)->Result<(),PersistenceError>{let url=format!("{}/rest/v1/paper_positions?id=eq.{}",self.base,p.id);let r=self.client.patch(url).header("apikey",&self.key).header("Authorization",format!("Bearer {}",self.key)).header("Content-Type","application/json").header("Prefer","return=minimal").json(&json!({"status":match p.state{crate::portfolio::PositionState::Closed=>"closed",crate::portfolio::PositionState::PartialExit=>"partial",_=>"open"},"exit_price":if matches!(p.state,crate::portfolio::PositionState::Closed){Some(p.peak_price)}else{None},"realized_pnl_sol":p.realized_pnl_sol,"peak_price":p.peak_price,"closed_at":if matches!(p.state,crate::portfolio::PositionState::Closed){Some(chrono::Utc::now())}else{None}})).send().await?;if r.status().is_success(){Ok(())}else{Err(PersistenceError::Status(r.status().as_u16(),r.text().await.unwrap_or_default()))}}
 pub async fn health(&self,component:&str,status:&str,latency_ms:Option<f64>)->Result<(),PersistenceError>{self.post("engine_health",json!({"component":component,"mode":"observe","rpc_ok":status=="healthy","pumpportal_ok":status=="healthy","rpc_latency_ms":latency_ms.map(|v|v as i64),"last_error":if status=="healthy"{Value::Null}else{json!(status)}})).await}
}
