"use client";
import {useEffect,useMemo,useState} from "react";
type D={tokens:any[];audits:any[];scenarios:any[];positions:any[];health:any[];markets:any[];serverTime:string};
export default function Home(){const[d,setD]=useState<D|null>(null);const[err,setErr]=useState("");const[selected,setSelected]=useState<string|null>(null);const load=async()=>{try{const r=await fetch("/api/overview",{cache:"no-store"});const j=await r.json();if(j.error)setErr(j.error);else{setErr("");setD(j)}}catch{setErr("Dashboard connection failed")}};useEffect(()=>{load();const x=setInterval(load,3000);return()=>clearInterval(x)},[]);
 const tokens=d?.tokens??[],audits=d?.audits??[],scenarios=d?.scenarios??[],positions=d?.positions??[],health=d?.health??[],markets=d?.markets??[];const latest=useMemo(()=>new Map(audits.map(a=>[a.mint,a])),[audits]);const marketMap=useMemo(()=>new Map(markets.map(m=>[m.mint,m])),[markets]);const selectedToken=selected?tokens.find(t=>t.mint===selected):null;const selectedAudit=selected?latest.get(selected):null;const selectedMarket=selected?marketMap.get(selected):null;const selectedScenarios=selected?scenarios.filter(s=>s.mint===selected):[];
 return <div><header className="topbar"><div className="brand">SOLANA INTELLIGENCE TERMINAL</div><div className="status">● PAPER/OBSERVE · {d?"CONNECTED":"CONNECTING"}</div></header><div className="layout"><aside className="sidebar"><nav className="nav"><a href="#opportunities">Live launches</a><a href="#security">Security audit</a><a href="#market">Market intelligence</a><a href="#scenarios">2x–100x research</a><a href="#paper">Paper trading</a><a href="#health">Engine health</a></nav></aside><main className="main"><div className="label">Real-time research control plane</div><h1 style={{fontSize:24,marginTop:4}}>Live Token Intelligence</h1>{err&&<div className="card"><span className="red">{err}</span><p className="muted">Configure SUPABASE_URL and the server-side SUPABASE_SECRET_KEY in Vercel.</p></div>}
 <div className="grid stats"><Stat label="Tokens observed" value={tokens.length}/><Stat label="Audits" value={audits.length}/><Stat label="Entry candidates" value={tokens.filter(t=>latest.get(t.mint)?.verdict==="ENTRY_CANDIDATE").length}/><Stat label="Blocked" value={audits.filter(a=>a.verdict==="BLOCKED").length}/><Stat label="Paper positions" value={positions.filter(p=>p.status!=="closed").length}/><Stat label="Last update" value={d?new Date(d.serverTime).toLocaleTimeString():"—"}/></div>
 <Section id="opportunities" title="Live launches"><div className="card">{!tokens.length?<Empty text="Waiting for real Pump.fun/PumpPortal events. No synthetic tokens are displayed."/>:<table className="table"><thead><tr><th>Token</th><th>Verdict</th><th>Audit</th><th>Rug risk</th><th>Honeypot risk</th><th>Scam risk</th></tr></thead><tbody>{tokens.slice(0,100).map(t=>{const a=latest.get(t.mint);return <tr key={t.mint} onClick={()=>setSelected(t.mint)} style={{cursor:"pointer"}}><td><b>${t.symbol||"UNKNOWN"}</b><div className="muted">{t.mint}</div></td><td><span className="pill">{a?.verdict||"OBSERVING"}</span></td><td>{a?.audit_score!=null?Math.round(a.audit_score)+"/100":"—"}</td><td>{a?.rug_confidence!=null?Math.round(a.rug_confidence)+"%":"—"}</td><td>{a?.honeypot_confidence!=null?Math.round(a.honeypot_confidence)+"%":"—"}</td><td>{a?.scam_confidence!=null?Math.round(a.scam_confidence)+"%":"—"}</td></tr>})}</tbody></table>}</div></Section>
 {selectedToken&&<Section id="market" title={`Token research · $${selectedToken.symbol||"UNKNOWN"}`}><div className="grid" style={{gridTemplateColumns:"repeat(4,1fr)"}}><Stat label="Price" value={selectedMarket?.price_usd!=null?`$${Number(selectedMarket.price_usd).toPrecision(6)}`:"—"}/><Stat label="Liquidity" value={selectedMarket?.liquidity_usd!=null?`$${Number(selectedMarket.liquidity_usd).toLocaleString()}`:"—"}/><Stat label="5m volume" value={selectedMarket?.volume_5m_usd!=null?`$${Number(selectedMarket.volume_5m_usd).toLocaleString()}`:"—"}/><Stat label="5m buys/sells" value={selectedMarket?`${selectedMarket.buys_5m}/${selectedMarket.sells_5m}`:"—"}/></div><div className="card" style={{marginTop:12}}><div className="label">Security evidence</div><pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit"}}>{JSON.stringify({verdict:selectedAudit?.verdict,audit_score:selectedAudit?.audit_score,rug_confidence:selectedAudit?.rug_confidence,honeypot_confidence:selectedAudit?.honeypot_confidence,scam_confidence:selectedAudit?.scam_confidence,reasons:selectedAudit?.reasons,evidence:selectedAudit?.evidence},null,2)}</pre></div></Section>}
 <Section id="security" title="Security audit"><div className="grid" style={{gridTemplateColumns:"repeat(4,1fr)"}}>{["Mint / freeze authority","Top-holder concentration","Sellability / honeypot","Creator / scam behavior"].map(x=><div className="card" key={x}><div className="label">{x}</div><div className="value" style={{fontSize:16}}>Evidence gated</div><div className="muted">Unknown evidence is not converted into a fake positive finding.</div></div>)}</div></Section>
 <Section id="scenarios" title="2x–100x scenario research"><div className="card">{!scenarios.length?<Empty text="Scenarios appear only when the evidence gate is satisfied."/>:<table className="table"><thead><tr><th>Token</th><th>Horizon</th><th>Target</th><th>Model output</th></tr></thead><tbody>{scenarios.slice(0,100).map(s=><tr key={s.id}><td>{s.mint.slice(0,10)}…</td><td>{s.horizon}</td><td>{s.multiple}x</td><td>{Math.round(Number(s.probability)*100)}%</td></tr>)}</tbody></table>}</div></Section>
 <Section id="paper" title="Paper trading"><div className="card">{!positions.length?<Empty text="No paper positions yet. Set TRADING_MODE=paper to enable simulated entries/exits."/>:<table className="table"><thead><tr><th>Token</th><th>Status</th><th>Entry</th><th>Peak</th><th>P&L SOL</th></tr></thead><tbody>{positions.map(p=><tr key={p.id}><td>{p.mint.slice(0,10)}…</td><td>{p.status}</td><td>{p.entry_price??"—"}</td><td>{p.peak_price??"—"}</td><td>{p.realized_pnl_sol??"—"}</td></tr>)}</tbody></table>}</div></Section>
 <Section id="health" title="Engine health"><div className="card">{!health.length?<Empty text="No heartbeat yet."/>:<table className="table"><thead><tr><th>Component</th><th>Status</th><th>Heartbeat</th><th>Latency</th></tr></thead><tbody>{health.map(h=><tr key={h.id}><td>{h.component}</td><td className={h.rpc_ok?"green":"yellow"}>{h.rpc_ok?"healthy":"degraded"}</td><td>{new Date(h.observed_at).toLocaleTimeString()}</td><td>{h.rpc_latency_ms==null?"—":h.rpc_latency_ms+" ms"}</td></tr>)}</tbody></table>}</div></Section>
 </main></div></div>}
function Stat(p:{label:string;value:any}){return <div className="card"><div className="label">{p.label}</div><div className="value">{p.value}</div></div>}function Empty(p:{text:string}){return <div className="empty">{p.text}</div>}function Section(p:{id:string;title:string;children:React.ReactNode}){return <section id={p.id} className="section"><h2>{p.title}</h2>{p.children}</section>}
