"use client";
import {useEffect,useState} from "react";
type D={tokens:any;audits:any;scenarios:any;positions:any;health:any;serverTime:string};
export default function Home(){
 const [d,setD]=useState<D|null>(null); const [err,setErr]=useState("");
 const load=async()=>{try{const r=await fetch("/api/overview",{cache:"no-store"});const j=await r.json();if(j.error)setErr(j.error);else setD(j)}catch{setErr("Dashboard connection failed")}};
 useEffect(()=>{load();const x=setInterval(load,3000);return()=>clearInterval(x)},[]);
 const tokens=Array.isArray(d?.tokens)?d?.tokens:[]; const audits=Array.isArray(d?.audits)?d?.audits:[]; const scenarios=Array.isArray(d?.scenarios)?d?.scenarios:[]; const positions=Array.isArray(d?.positions)?d?.positions:[]; const health=Array.isArray(d?.health)?d?.health:[]; const latest=new Map(audits.map((a:any)=>[a.mint,a]));
 return <div><header className="topbar"><div className="brand">SOLANA INTELLIGENCE TERMINAL</div><div className="status">● PAPER MODE · {d?"CONNECTED":"CONNECTING"}</div></header><div className="layout"><aside className="sidebar"><nav className="nav"><a href="#">Overview</a><a href="#opportunities">Opportunities</a><a href="#security">Security Audit</a><a href="#scenarios">Scenarios</a><a href="#paper">Paper Trading</a><a href="#health">Engine Health</a></nav></aside><main className="main"><div className="label">Research control plane</div><h1 style={{fontSize:24,marginTop:4}}>Live Token Intelligence</h1>{err&&<div className="card"><span className="red">{err}</span><p className="muted">Configure SUPABASE_URL and SUPABASE_SECRET_KEY on the Vercel server. Never expose the secret key in browser code.</p></div>}
 <div className="grid stats"><Stat label="Tokens observed" value={tokens.length}/><Stat label="Audits" value={audits.length}/><Stat label="Candidates" value={tokens.filter((t:any)=>latest.get(t.mint)?.verdict==="ENTRY_CANDIDATE").length}/><Stat label="Critical flags" value={audits.filter((a:any)=>(a.critical_flags||[]).length>0).length}/><Stat label="Paper positions" value={positions.filter((p:any)=>p.status!=="closed").length}/><Stat label="Last update" value={d?new Date(d.serverTime).toLocaleTimeString():"—"}/></div>
 <Section id="opportunities" title="Live opportunities"><div className="card">{!tokens.length?<Empty text="Waiting for the Rust engine. No synthetic tokens are displayed."/>:<table className="table"><thead><tr><th>Token</th><th>Verdict</th><th>Rug</th><th>Honeypot</th><th>Scam</th></tr></thead><tbody>{tokens.map((t:any)=><tr key={t.mint}><td><b>{"$"+(t.symbol||"UNKNOWN")}</b><div className="muted">{t.mint.slice(0,10)}…</div></td><td><span className="pill">{latest.get(t.mint)?.verdict||"OBSERVING"}</span></td><td>{latest.get(t.mint)?.rug_confidence!=null?Math.round(latest.get(t.mint).rug_confidence)+"%":"—"}</td><td>{latest.get(t.mint)?.honeypot_confidence!=null?Math.round(latest.get(t.mint).honeypot_confidence)+"%":"—"}</td><td>{latest.get(t.mint)?.scam_confidence!=null?Math.round(latest.get(t.mint).scam_confidence)+"%":"—"}</td></tr>)}</tbody></table>}</div></Section>
 <Section id="security" title="Security audit"><div className="grid" style={{gridTemplateColumns:"repeat(4,1fr)"}}>{["Mint / freeze authority","Honeypot / sellability","Rug / holder risk","Creator / scam behavior"].map(x=><div className="card" key={x}><div className="label">{x}</div><div className="value" style={{fontSize:16}}>Evidence required</div><div className="muted">Missing critical evidence fails closed.</div></div>)}</div></Section>
 <Section id="scenarios" title="2x–100x scenario research"><div className="card">{!scenarios.length?<Empty text="No forecast exists until an audited token has enough real market data."/>:<table className="table"><thead><tr><th>Token</th><th>Horizon</th><th>Target</th><th>Probability</th><th>Model</th></tr></thead><tbody>{scenarios.slice(0,40).map((s:any)=><tr key={s.id}><td>{s.mint.slice(0,10)}…</td><td>{s.horizon}</td><td>{s.multiple+"x"}</td><td>{s.probability!=null?Math.round(s.probability*100)+"%":"—"}</td><td>{s.model_version}</td></tr>)}</tbody></table>}</div></Section>
 <Section id="paper" title="Paper trading"><div className="card">{!positions.length?<Empty text="No paper positions yet. Live-money execution remains locked."/>:<table className="table"><thead><tr><th>Token</th><th>Status</th><th>Entry</th><th>Exit</th><th>ROI</th></tr></thead><tbody>{positions.map((p:any)=><tr key={p.id}><td>{p.mint.slice(0,10)}…</td><td>{p.status}</td><td>{p.entry_price_usd??"—"}</td><td>{p.exit_price_usd??"—"}</td><td>{p.realized_roi_pct==null?"—":p.realized_roi_pct+"%"}</td></tr>)}</tbody></table>}</div></Section>
 <Section id="health" title="Engine health"><div className="card">{!health.length?<Empty text="No engine heartbeat received."/>:<table className="table"><thead><tr><th>Component</th><th>Status</th><th>Heartbeat</th><th>Latency</th></tr></thead><tbody>{health.map((h:any)=><tr key={h.component}><td>{h.component}</td><td className={h.status==="healthy"?"green":"yellow"}>{h.status}</td><td>{new Date(h.last_heartbeat).toLocaleTimeString()}</td><td>{h.latency_ms==null?"—":h.latency_ms+" ms"}</td></tr>)}</tbody></table>}</div></Section>
 </main></div></div>};
function Stat(p:{label:string;value:any}){return <div className="card"><div className="label">{p.label}</div><div className="value">{p.value}</div></div>}
function Empty(p:{text:string}){return <div className="empty">{p.text}</div>}
function Section(p:{id:string;title:string;children:React.ReactNode}){return <section id={p.id} className="section"><h2>{p.title}</h2>{p.children}</section>}