-- Run once on the trading Supabase project after the original schema.
create table if not exists public.token_audits(id uuid primary key default gen_random_uuid(),mint text not null references public.tokens(mint),generated_at timestamptz not null default now(),verdict text not null,audit_score numeric not null,rug_confidence numeric not null,honeypot_confidence numeric not null,scam_confidence numeric not null,reasons jsonb not null default '[]'::jsonb,evidence jsonb not null default '[]'::jsonb,model_version text not null default 'evidence-v1');
create table if not exists public.market_snapshots(id uuid primary key default gen_random_uuid(),mint text not null references public.tokens(mint),observed_at timestamptz not null default now(),price_usd numeric,fdv_usd numeric,liquidity_usd numeric,volume_5m_usd numeric,volume_1h_usd numeric,buys_5m bigint,sells_5m bigint,dex text,pool_address text);
create table if not exists public.market_candles(id uuid primary key default gen_random_uuid(),mint text not null references public.tokens(mint),interval text not null,bucket_start timestamptz not null,open numeric,high numeric,low numeric,close numeric,volume_usd numeric,buy_volume_usd numeric,sell_volume_usd numeric,trades bigint,unique_buyers bigint,unique_sellers bigint,unique(mint,interval,bucket_start));
create table if not exists public.scenario_forecasts(id uuid primary key default gen_random_uuid(),mint text not null references public.tokens(mint),generated_at timestamptz not null default now(),multiple numeric not null,probability numeric not null,horizon text not null,model_version text not null default 'evidence-v1',basis jsonb not null default '[]'::jsonb);
alter table public.paper_positions add column if not exists realized_roi_pct numeric;
alter table public.paper_positions add column if not exists peak_price numeric;
alter table public.orders add column if not exists jito_tip_lamports bigint;
alter table public.executions add column if not exists bundle_id text;
alter table public.executions add column if not exists jito_tip_lamports bigint;
alter table public.market_events add column if not exists trader text;
alter table public.security_snapshots add column if not exists evidence jsonb not null default '[]'::jsonb;
alter table public.pools add column if not exists price_usd numeric;
alter table public.pools add column if not exists volume_5m_usd numeric;
alter table public.pools add column if not exists volume_1h_usd numeric;
alter table public.engine_health add column if not exists component text;
alter table public.engine_health add column if not exists observed_at timestamptz not null default now();
alter table public.engine_health add column if not exists mode text default 'observe';
alter table public.engine_health add column if not exists rpc_ok boolean default false;
alter table public.engine_health add column if not exists pumpportal_ok boolean default false;
alter table public.engine_health add column if not exists rpc_latency_ms bigint;
alter table public.engine_health add column if not exists last_error text;
alter table public.tokens enable row level security;
alter table public.token_audits enable row level security;
alter table public.market_snapshots enable row level security;
alter table public.market_candles enable row level security;
alter table public.scenario_forecasts enable row level security;
